model:
    backbone: "convnext_tiny" # "efficientnet-b0" #resnet18 - resnet50 - efficientnet-b0
    embeddings: 128
    
dataset:  
    batchsampler:
        classes_per_batch: 35
        samples_per_class: 5
train:
    loss:
        name: 'pnploss'
        adaptive_margin: False
    learning_rate: 0.015
    momentum: 0.9
    epoch: 4000
    warmup_steps: 500
    opt_level: 'O2'

output_folder: '/home/fishial/Fishial/output/classification'
file_name: 'model'
dataset_fo: 'classification-v0.8.1_40_250_TRAIN'
device: 'cuda'
checkpoint: ''