model:
    backbone: "resnet18"
    embeddings: 256
    
dataset:
    train:
        path: '/home/codahead/Fishial/FishialReaserch/datasets/fishial_75_V1.0'
        json_path: 'data_train.json'
    test:
        path: '/home/codahead/Fishial/FishialReaserch/datasets/fishial_75_V1.0'
        json_path: 'data_test.json'
  
    batchsampler:
        classes_per_batch: 5
        samples_per_class: 15
train:
    loss:
        name: 'qudruplet'
        adaptive_margin: False
    learning_rate: 0.012
    momentum: 0.9
    epoch: 1200
    warmup_steps: 500
    opt_level: 'O2'

output_folder: '/home/codahead/Fishial/FishialReaserch/output/train_results/resnet_18_98_finall_update'
file_name: 'full_256'
device: 'cuda'
checkpoint: '/home/codahead/Fishial/FishialReaserch/output/train_results/resnet_18_98_finall/full_256.ckpt'